#!/bin/bash
# Build "Dwn SHIFT.app": a double-clickable Mac app for the game.
#
#   tools/build_mac_app.sh            -> ./Dwn SHIFT.app (drag it to the Dock or /Applications)
#
# The app serves this folder with play.py on its own port and opens it in a
# dedicated Chrome window (app mode: no tabs, no toolbar, full screen). That
# Chrome runs from its own profile, so no extensions, no other tabs competing for
# the GPU, and background throttling is off. The game files stay in this folder:
# edits show up the next time you launch. Rebuild if you move the folder.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/Dwn SHIFT.app"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
[ -x "$CHROME" ] || { echo "Google Chrome is required: $CHROME not found" >&2; exit 1; }

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Dwn SHIFT</string>
  <key>CFBundleDisplayName</key><string>Dwn SHIFT</string>
  <key>CFBundleIdentifier</key><string>local.dwnshift.game</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>DwnShift</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSApplicationCategoryType</key><string>public.app-category.racing-games</string>
  <key>NSHighResolutionCapable</key><true/>
</dict></plist>
PLIST

cat > "$APP/Contents/MacOS/DwnShift" <<LAUNCH
#!/bin/bash
# Dwn SHIFT launcher (generated by tools/build_mac_app.sh).
GAME="$ROOT"
PORT=8765
PROFILE="\$HOME/Library/Application Support/Dwn SHIFT/Chrome"
LOG="\$HOME/Library/Logs/Dwn SHIFT.log"
mkdir -p "\$PROFILE" "\$(dirname "\$LOG")"
cd "\$GAME" || { osascript -e 'display alert "Dwn SHIFT" message "The game folder moved. Run tools/build_mac_app.sh again from its new place."'; exit 1; }

# The game server (quiet, no browser of its own). Reuse one already running on the port.
if ! curl -s -o /dev/null "http://127.0.0.1:\$PORT/"; then
  PORT=\$PORT NO_OPEN=1 /usr/bin/python3 play.py >>"\$LOG" 2>&1 &
  SERVER=\$!
  trap 'kill \$SERVER 2>/dev/null' EXIT
  for i in \$(seq 50); do curl -s -o /dev/null "http://127.0.0.1:\$PORT/" && break; sleep 0.1; done
fi

# A separate Chrome instance (own profile) in app mode, tuned for a game:
# GPU always on, never throttled when another window covers it, sound without a click first.
"$CHROME" \\
  --user-data-dir="\$PROFILE" \\
  --app="http://127.0.0.1:\$PORT/" \\
  --start-fullscreen \\
  --no-first-run --no-default-browser-check --disable-extensions --disable-sync \\
  --disable-component-update --disable-default-apps --disable-translate \\
  --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy \\
  --disable-background-timer-throttling --disable-renderer-backgrounding \\
  --disable-backgrounding-occluded-windows \\
  --autoplay-policy=no-user-gesture-required \\
  >>"\$LOG" 2>&1
LAUNCH
chmod +x "$APP/Contents/MacOS/DwnShift"

# Icon: the concept art, centre-cropped to a square.
ICON_SRC="$ROOT/gameconcept.png"
if [ -f "$ICON_SRC" ]; then
  TMP="$(mktemp -d)"; SET="$TMP/AppIcon.iconset"; mkdir -p "$SET"
  H=$(sips -g pixelHeight "$ICON_SRC" | awk '/pixelHeight/{print $2}')
  sips -c "$H" "$H" "$ICON_SRC" --out "$TMP/square.png" >/dev/null
  for s in 16 32 128 256 512; do
    sips -z $s $s "$TMP/square.png" --out "$SET/icon_${s}x${s}.png" >/dev/null
    sips -z $((s*2)) $((s*2)) "$TMP/square.png" --out "$SET/icon_${s}x${s}@2x.png" >/dev/null
  done
  iconutil -c icns "$SET" -o "$APP/Contents/Resources/AppIcon.icns"
  rm -rf "$TMP"
fi

touch "$APP"
echo "Built: $APP"
